### ISSUE TITLE
Juego Jaca terminado

### ISSUE THREAD

**Issue by NadiaCorrea** [NadiaCorrea/entorno_programacion#1]
Buenas noches, Inma.
He terminado con el juego aunque aún me faltan los tests.

Por favor, déjame saber si tengo que hacer algún cambio.

Un saludo.
Nadia.

**Comment by ioliasa** [comment]
La idea es que con las pruebas veais si funciona bien o no, y no necesitéis a alguien que os diga si está bien o no
